"""
Test Utility for Window Backend Interface

Purpose: Verify interface compilation and basic expectations

File Metadata:
- Generated by: Claude Opus 4 (Anthropic AI)
- Generation Date: 2025-07-19

Primary Contributors:
- AI Model: Claude Opus 4
- Human Developer: Amir Farhadi

"""

from window_backend import IWindowBackend

def test_interface_basic():
    """Verify basic interface expectations"""
    # Verify interface is importable
    assert IWindowBackend is not None, "Interface should be importable"

    # Verify cannot instantiate abstract class
    try:
        backend = IWindowBackend()
        assert False, "Should not be able to instantiate abstract class"
    except TypeError:
        pass

def test_interface_methods():
    """Check that all expected methods are defined"""
    required_methods = [
        'get_all_windows',
        'get_window_title',
        'focus_window',
        'get_window_position',
        'move_window',
        # Add other method names from your interface
    ]

    for method in required_methods:
        assert hasattr(IWindowBackend, method), f"Missing method: {method}"

def main():
    """Run all tests"""
    test_interface_basic()
    test_interface_methods()
    print("✅ All interface tests passed successfully!")

if __name__ == '__main__':
    main()