_enabled_ordered = ["Alphabet", "Navigation", "NavigationNon", "Numbers", "Punctuation", "Keyboard", "CasterRule", "CasterMicRule", "SudokuGridRule", "HistoryRule", "ChainAlias", "Alias", "BringRule", "Again", "GrammarActivatorRule", "HooksActivationRule", "TransformersActivationRule", "DictationSinkRule", "VSCodeCcrRule", "VSCodeNonCcrRule", "WindowManagementRule", "FirefoxExtendedRule", "VSCodeExtendedCcrRule", "GlobalCCRExtendedRule", "FileDialogRule", "VLCRule", "HardwareRule", "RainbowGridRule", "OBSStudioRule", "SumatraRule", "GlobalNonCCRExtendedRule", "MSTeamsClassicRule", "YoutubeRule", "GeminiRule", "ChatGPTRule", "ClipchampRule", "FirefoxCcrRule", "VsCodeExtendedRule", "TextManipulation", "CustomMSWordRule", "CustomOutlookRule", "MSWordCcrRule", "CustomGitHubDeskRule", "CopilotRule", "CustomMouseAlternativesRule", "ElementMatrixRule", "CustomMSTeamsRule", "EnableViaCamRule", "TaskbarRule", "CustomIERule", "WordRule"]
_internal = ["GrammarActivatorRule", "HooksActivationRule", "TransformersActivationRule", "ManualGrammarReloadRule"]

[whitelisted]
Alphabet = true
Navigation = true
NavigationNon = true
Numbers = true
Punctuation = true
Keyboard = true
CasterRule = true
CasterMicRule = true
HardwareRule = true
MouseAlternativesRule = true
WindowManagementRule = true
DouglasGridRule = true
RainbowGridRule = true
SudokuGridRule = true
HMCRule = false
HMCConfirmRule = false
HMCDirectoryRule = false
HMCHistoryRule = false
HMCLaunchRule = false
HMCSettingsRule = false
HistoryRule = true
ChainAlias = true
Alias = true
BringRule = true
Again = true
LegionGridRule = true
IERule = false
SikuliRule = true
SikuliManagementRule = true
JetbrainsRule = true
CSS = false
JiraRule = false
ChromeRule = false
FirefoxRule = true
GitterRule = true
MSTeamsRule = true
WebexTeamsRule = false
AtomRule = false
EmacsRule = false
FlashDevelopRule = false
LyxRule = false
MSVCRule = false
NPPRule = false
RStudioRule = false
SQLDeveloperRule = false
SSMSRule = false
SublimeRule = false
TyporaRule = false
UnityRule = false
VisualStudioRule = false
EclipseCCR = false
EclipseRule = false
VSCodeCcrRule = true
VSCodeNonCcrRule = true
fmanRule = false
TotalCommanderRule = false
SyncDirsRule = true
GitHubDeskRule = false
KDiff3Rule = true
ExcelRule = false
OutlookRule = true
AcrobatRule = false
FoxitRule = false
WindowsSpeechRecognitionRule = true
DragonRule = true
SpellingWindowRule = true
GitBashRule = true
FileDialogueRule = false
MSWordRule = true
Bash = true
CPP = true
CSharp = true
Dart = true
Go = true
Haxe = true
HTML = true
Javascript = true
Java = true
JavaNon = true
LaTeX = true
Markdown = true
Matlab = false
MatlabNon = false
Prolog = false
PrologNon = true
Python = true
PythonNon = true
Rust = false
RustNon = false
Rlang = false
SQL = false
VHDL = false
VHDLnon = false
VoiceDevCommands = true
DictationSinkRule = true
TextManipulation = true
FirefoxExtendedRule = true
VSCodeExtendedCcrRule = true
GlobalCCRExtendedRule = true
ExplorerRule = false
FileDialogRule = true
VLCRule = true
OBSStudioRule = true
SumatraRule = true
CustomGitbashRule = true
GlobalNonCCRExtendedRule = true
MSTeamsClassicRule = true
CustomMarkdown = true
YoutubeRule = true
GeminiRule = true
ChatGPTRule = true
ClipchampRule = true
FirefoxCcrRule = true
CustomIERule = true
VsCodeExtendedRule = true
CustomMSWordRule = true
CustomOutlookRule = true
MSWordCcrRule = true
CustomGitHubDeskRule = true
CopilotRule = true
CustomMouseAlternativesRule = true
ElementMatrixRule = true
CustomMSTeamsRule = true
EnableViaCamRule = true
TaskbarRule = true
WordRule = true
